server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
        - id: payment_route2
          uri: http://localhost:8001
          #          filters:
          #            - AddRequestParameter=X-Request-Id, 1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id,值为1024
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka